# 公共属性配置
debug: false
server:
  port: 8080
  context-path: /api
logging:
  config: classpath:logback-spring.xml

spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    show-sql: false
    open-in-view: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/jumao?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false
    username: root
    password: root
    initial-size: 10
    min-idle: 10
    max-active: 40
    max-wait: 60000
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 'X'
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    filters: stat, wall, log4j
    connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=3000;druid.stat.logSlowSql=true;
    servlet-username: DEVELOPERS
    servlet-password: JUST_DO_IT
    servlet-reset-enable: false
    servlet-url: /druid/*
    filter-pattern: /*
    filter-exclusions: /druid/*,*.html,*.js,*.css,*.gif,*.jpg,*.jpeg,*.png,*.ico

application:
  pageable:
    default-page: 0
    default-size: 10
    min-size: 10
    max-size: 50

---
# 开发私有属性环境配置
spring:
  profiles: dev

---
# 生产环境私有属性配置
spring:
  profiles: prod

